export const ADMIN_USERS_SUCCESS = 'ADMIN_USERS_SUCCESS'
export const ADMIN_USERS_ERROR = 'ADMIN_USERS_ERROR'

export const ADMIN_CLOCKS_SUCCESS = 'ADMIN_CLOCKS_SUCCESS'
export const ADMIN_CLOCKS_ERROR = 'ADMIN_CLOCKS_ERROR'

export const ADMIN_CLOCK_CREATE_SUCCESS = 'ADMIN_CLOCK_CREATE_SUCCESS'
export const ADMIN_CLOCK_CREATE_ERROR = 'ADMIN_CLOCK_CREATE_ERROR'

export const ADMIN_LINK_CLOCK_SUCCESS = 'ADMIN_LINK_CLOCK_SUCCESS'
export const ADMIN_LINK_CLOCK_ERROR = 'ADMIN_LINK_CLOCK_ERROR'

