export const ADMIN_USERS_SUCCESS = 'ADMIN_USERS_SUCCESS'
export const ADMIN_USERS_ERROR = 'ADMIN_USERS_ERROR'

export const ADMIN_CLOCKS_SUCCESS = 'ADMIN_CLOCKS_SUCCESS'
export const ADMIN_CLOCKS_ERROR = 'ADMIN_CLOCKS_ERROR'
